default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'sifa_chat_dev') %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'sifa_chat_test') %>

staging:
  <<: *default
  database: sifa_staging
  username: rails
  password: <%= ENV['SIFA_STAGING_DATABASE_PASSWORD'] %>
  
production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'sifa_chat_production') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'sifa_chat_prod') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'sifa_chat_prod') %>
